@extends('layouts.main') 
@section('content')
<!-- Start Main -->
<main class="static-main">
    <div class="container">
	<h1>Opšti uslovi korišćenja</h1>

	<p>Dobro došli na Playpoint Srbija na www.playpoint.mobi. Molimo pročitajte pažljivo ove Opšte uslove korišćenja (‘Uslovi’). Preveli smo ove Opšte uslove korišćenja na vaš lokalni jezik, ali će Opšti uslovi korišćenja na engleskom uvek prevagnuti. Imajte u vidu da Usluge koje su obuhvaćene ovim sporazumom ne možete otkazati ni na koji drugi način nego što je opisano u ovim Uslovima kada je počelo primenjivanje tih Usluga. Ukoliko se ne slažete sa ovim Uslovima, ne treba da nastavljate na ovom sajtu s registracijom ili s bilo kojim pokušajem pristupa Uslugama ili njihovom korišćenju koje pokrivaju ovi Uslovi. U suprotnom se slažete s korišćenjem Usluga pod uslovima utvrđenim ovim sporazumom. S vremena na vreme će možda biti potrebno da izmenimo ove Uslove i bilo koja takva promena će biti sprovedena u saglasnosti s ovim Uslovima. Molimo da proveravate redovno na ovom veb sajtu jer ćemo vas tu obaveštavati o svakoj takvoj promeni.
	</p>
	<h2>1. Opis i tipovi usluga
	</h2>
	<p>Playpoint Srbija (‘Kompanija’, ‘Mi’) je razvio niz sadržaja za mobilne telefone koji se mogu preuzeti, onlajn kao i putem bežične komunikacije, kao što su melodije, igrice, pozadine i SMS-usluge (kolektivno ‘Usluge’) za određene kompatibilne mobilne uređaje. Ove usluge vam nudiRoot Technologies B.V, 4001 KZ Tiel, Nederland. Usluge koje su vam dostupne podležu ovim Uslovima. Usluge će uključivati pristup informacijama, podacima, tekstu, softveru, muzici, melodijama, fotografijama, grafici, videu, porukama ili drugim materijalima. Usluge nisu namenjene za davanje saveta u vezi poreza, računovodstva ili kao ni saveta u vezi pogodnosti ili profitabilnosti vrednosnih hartija ili investicija, ni zdravstvenih ili medicinskih saveta, niti bilo kakvih drugih saveta lične prirode. Usluge mogu da uključuju i pristup sadržajima i uslugama nezavisne treće strane. Nakon pravilnog upisa i uplate, biće vam dozvoljeno da preuzmete usluge preko kompatibilnog mobilnog telefona i drugih kompatibilnih uređaja. Kompanija nudi svoje usluge (a) putem tekućeg pretplatničkog modela(b) kao kreditni model u kojem je ponuđen paket kredita za određeni broj individualnih preuzimanja na osnovu (nedeljne) mogućnosti obnavljanja pretplate (c) putem jednokratnog (jedna upotreba) modela preuzimanja. Osim ako nije eksplicitno drugačije naznačeno, nikakva informacija predstavljena u Uslugama ili u vezi Usluga se neće smatrati obavezujućom ponudom od strane Kompanije, nego kao poziv da naručite usluge. Kompanija će imati pravo da pruži usluge, kako smatra da je najbolje ali će pokušati da obezbedi da Usluge nisu manjeg standarda nego na dan kad su ovi Uslovi stupili na snagu. U zavisnosti od vaših prava na nadoknadu troškova u saglasnosti s ovim Uslovima , Kompanija zadržava pravo da modifikuje ili prekine, privremeno ili trajno, Usluge koje vam pruža. Ukoliko bi Usluge bile trajno prekinute s naše strane, mi ćemo vas o toj činjenici obavestiti.
	</p>

	<h2>2. Registracija i opšti pristup uslugama
	</h2>

	<p>Da bi mogli koristiti Usluge Vi (1) morate imati najmanje 18 godina ili imati saglasnost pretplatnika/vlasnika naloga mobilnih usluga da se prijavite i koristite usluge u njegovo ime (2) da se slažete sami i u ime pretplatnika/vlasnika naloga da se obavezujete ovim Uslovima. Prihvatate da vam je ponuđena mogućnost da pročitate i prihvatite Uslove pre korišćenja Usluga; ukoliko se ne slažete; nemojte koristiti usluge. Kada se prijavite za i / ili koristite Usluge priznajete i potvrđujete da ste prihvatili ove Uslove i da ste saglasni sa uslovima koji su primenljivi na vašu situaciju, kao što je gore naznačeno. Slažete se da je svaka osoba koja zahteva takve usluge vaš zastupnik s punim pravom da nastupa u vaše ime u vezi tih Usluga. Ovaj sporazum se poništava gde je zabranjeno. Osim ako eksplicitno nije navedeno drugačije, bilo koje nove ili dodatne funkcije koje uvećavaju ili poboljšavaju postojeće Usluge, uključujući i uvođenje novih Usluga, podlegaće Uslovima.
	</p>
	<h2>3. Obaveza registracije; Lični podaci
	</h2>

	<p>Na vaš zahtev, Kompanija može da vas registruje kao korisnika i pruži vam pristup Uslugama davanjem ličnog korisničkog imena i lozinke. Vi ste isključivo odgovorni za održavanje poverljivosti bilo koje moguće lozinke i naloga. Kompanija će možda morati da promeni korisnička imena vezana za određene aspekte njenih usluga i zadržava pravo da to uradi (bićete informisani ukoliko je to potrebno). Da bi se mogla garantovati sigurna upotreba usluga, kao i plaćanje primenljivih troškova, vi ćete garantovati za sva vremena da su: (a) lične informacije (u daljem tekstu kao ‘lični podaci’) koje ste uneli prilikom registracije tačni i potpuni. Ukoliko kompanija, po sopstvenom nahođenju, smatra da lični podaci nisu tačni ili potpuni, kompanija ima pravo da suspenduje ili ukine vaš nalog i da prekine i sadašnje i buduće korišćenje Usluga, ili bilo koje komponente istih. Vi ste odgovorni za održavanje tajnosti bilo kojih lozinki i/ili naloga koji su vam dodeljeni od strane Kompanije, i u potpunosti ste odgovorni za sve izvršene delatnosti koje uključuju korišćenje lozinke i naloga. Vi preduzimate da na kraju svakog korišćenja zatvorite svoj nalog (zatvaranjem brauzera) i da kontaktirate Kompaniju ukoliko primetite ili posumnjate da je vaša lozinka ili vaš nalog neovlašćeno korišćen, ili da sigurnost ili zaštita vaših ličnih podataka nije više zagarantovana iz bilo kog drugog razloga. Kompanija ne može i neće biti odgovorna za bilo koji gubitak ili štetu koji proističu zbog vašeg nepoštovanja ovog Dela. Kompanija može da vam pruži pristup nekim Uslugama da se niste registrovali kao korisnik, kao što je prijavljivanje za Usluge preko vašeg mobilnog telefona. U svakom takvom slučaju vaša identifikacija se zasniva na sredstvima identifikacije koje mi smatramo odgovarajućim, kao što je broj mobilnog telefona. Slažete se da takve informacije mogu biti prikupljene i otkrivene Kompaniji i korišćene u saglasnosti s Delom “Privatnost i procesiranje podataka” ovih Uslova.
	</p>
	<h2>4. Pristup tekućem modelu pretplate
	</h2>
	<p>Tekuća pretplata će početi kada vam je Kompanija na vaš zahtev pružila pristup Uslugama. Pristup Uslugama može biti pružen isporukom Usluga za preuzimanje (npr. isporukom pozadine, melodije ili igrice za mobilni telefon), pružanjem pristupa Uslugama (npr. omogućavanjem MSISDN (digitalni mrežni broj integrisanih usluga mobilnih stanica) za ove Usluge) ili omogućavanjem preuzimanja Usluga (npr. isporučivanjem linka WAP-Push ili PIN-a za preuzimanje Usluga na veb sajtu Kompanije). Sporazum o pretplati će ostati na snazi do prekidanja i/ili otkazivanja od strane vas ili Kompanije u saglasnosti sa Delom “Vaše odgovornosti’ ovih Uslova. Sporazumi o Uslugama Kompanije i treće nezavisne strane koji su postali dostupni putem Usluga će početi kada je Kompanija ili treća strana prihvatila vašu narudžbinu za isto ili vam je pružila usluge na osnovu vaše narudžbine. Ovaj sporazum će ostati na snazi sve dok ga vi ili Kompanija ne prekinete u skladu sa Delom “Prekid i otkazivanje usluga, pravo opozivanja” ovih Uslova.
	</p>
	<h2>5. Pristup kreditnom modelu
	</h2>
	<p>Tekuća pretplata će početi kada vam je Kompanija isporučila određeni broj kredita. Nedeljni kreditni model uključuje određeni definisani broj kredita koji vam daju pravo preuzimanja, primanja i/ili pristupa tom određenom broju usluga za nedeljni fiksni iznos. Nakon stupanja na snagu sporazuma za pretplatu, Kompanija će svake nedelje prebaciti kredite za preuzimanje na vaš nalog. Obezbeđivanje kredita i stvaranje mogućnosti za preuzimanje, primanje i/ili pristupanje uslugama se nudi po fiksnoj ceni. Nedeljni fiksni iznos će se naplaćivati svake nedelje, vaš sporazum o pretplati je važeći bez obzira da li ste preuzimali bilo koje usluge u toku bilo kog perioda pretplate; za nedeljni fiksni iznos će se u obzir uzimati isključivo nedeljno pružanje prava na preuzimanje, primanje i/ili pristupanje Uslugama za preuzimanje. Broj kredita za preuzimanje će biti umanjen za broj preuzetih Usluga. Krediti se ne mogu prenositi i zavise od tipa vašeg sporazuma o pretplati. Ako ne iskoristite/upotrebite sve svoje kredite u toku perioda pretplate, neiskorišćeni krediti će se ili (a) prebaciti na sledeći period pretplate i ostaće na vašem nalogu dok ne budu iskorišćeni/upotrebljeni ili do isticanja ili prekidanja vašeg sporazuma o pretplati ili (b) ističu svakih 30 dana nakon dodele. Ukoliko preuzmete Usluge koje prevazilaze količinu dozvoljenu sporazumom o pretplati , onda se slažete da platite primenljivu maloprodajnu cenu Kompanije za dodatna preuzimanja. Krediti se mogu koristiti samo za preuzimanje usluga koje nudi Kompanija.
	</p>
	<h2>6. Pristup jednokratnom (jedna upotreba) modelu preuzimanja
	</h2>
	<p>Jednokratni (jedna upotreba) model preuzimanja uključuje da možete da odaberete bilo koju od jednokratnih Usluga koju želite da preuzmete. Mogućnost preuzimanja, primanja i/ili pristupanja Uslugama je ponuđena po fiksnom iznosu, kao što je saopšteno na našem veb sajtu. Nema pretplate i nisu uključeni nikakvi troškovi koji se ponavljaju.
	</p>

	<h2>7. Troškovi
	</h2>
	<p>Cene za Usluge su dostupne na veb sajtu Kompanije. Nedeljni iznos će biti naplaćen za svaki period pretplate od stupanja sporazuma na snagu. Platićete Kompaniji za Usluge i upotrebu u skladu sa cenovnikom na snazi u vreme vaše narudžbine. Osim ako nije drugačije naznačeno, iznos će biti naplaćen preko vašeg računa za mobilni telefon ili odbijen od vašeg balansa. Dodatni porez i odvojene naplate od mobilnog operatera za tekstualne poruke WAP/GPRS/3G mogu da se primene na vašu upotrebu Usluga. Gde je primenljivo, troškovi mogu da se plate i korišćenjem kredita, kreditnom karticom, bankovnim transferom ili putem vašeg korisničkog naloga. Različite metode plaćanja su naznačene tokom procesa naručivanja za Usluge koje odaberete. Kompanija može da vam pošalje račun za troškove treće strane čije su usluge dostupne kroz Usluge ukoliko je ovo dogovoreno s trećom stranom. Za takve troškove će biti poslat račun u skladu sa cenama takve treće strane. Svi iznosi, uključujući iznose za postojeće sporazume o pretplati, mogu da se promene nakon obaveštenja od strane Kompanije. Kompanija će vas obavestiti u razumnom roku o takvoj promeni. Ukoliko ne prihvatate nove cene (koje će biti primenljive samo na potencijalnoj osnovi), možete otkazati svoju pretplatu i/ili svoj nalog što će stupiti na snagu odmah nakon prekidanja.
	</p>

	<h2>8. Vaše odgovornosti
	</h2>
	<p>Da biste koristili usluge, morate imati pretplatu na mobilne komunikacije sa važeći bežičnim operaterom ili u suprotnom imati pristup mreži mobilne komunikacije kojima Kompanija čini svoje usluge dostupnima kao i bilo koje usluge bežičnih operatera neophodnih za preuzimanje sadržaja, i plaćanje bilo kojih (operatera bežičnih usluga) cena usluga vezanih za bilo koji takav pristup. Morate imati Internet konekciju u funkciji instaliranu na vašem mobilnom telefonu (WAP, GPRS, UMTS). Vaš mobilni telefon mora da ima mogućnost primanja tekstualnih poruka, melodija, igrica za mobilne, video i/ili kolor grafika. Dodatno, vaš mobilni telefon mora da ima mogućnost da putem Interneta preuzima melodije, igrice za mobilne, video, kolor grafike ili druge usluge za preuzimanje. Kompanija vas neće refundirati ako preuzimate ili pokušate da preuzmete usluge na nekompatibilne telefone ili bežične operatere ili ako vaš mobilni telefon nema omogućen Internet. Za uputstva, molimo proverite veb sajt vašeg bežičnog operatera ili veb sajt proizvođača mobilnog telefona. Dodatno, morate se postarati za svu opremu i softver neophodan za povezivanje na usluge. Vaša je odgovornost da se postarate da oprema i/ili softver ne smetaju ili se mešaju s poslovanjima Kompanije. Kompanija će imati pravo da trenutno ukine Usluge za opremu ili softver koji prouzrokuje smetnje i da trenutno prekine ovaj sporazum. Usluge su samo za ličnu upotrebu i ne mogu se dodeliti ili preneti na neki drugi broj mobilnog telefona, osobu ili entitet, niti vi možete da date drugoj osobi ili entitetu pristup Vašim Uslugama, ni direktno ni indirektno. Bilo koje ponašanje ili aktivnost za koje verujemo da ograničava ili sprečava bilo kog drugog korisnika u pristupanju, korišćenju ili uživanju Usluga neće biti dozvoljeno. Slažete se da koristite Usluge samo u zakonite svrhe.
	</p>

<h2>9. Prava intelektualne svojine
</h2>
	<p>Osim ako je drugačije navedeno u ovom tekstu, sva prava i interesi za i prema bilo kojoj intelektualnoj svojini, vlasnička prava ili druga prava koja se odnose na nematerijalnu imovinu koja se koristila, razvijala, obuhvatala, bila otelotvorena ili se praktikovala u vezi bilo koje Usluge ( "Prava intelektualne svojine Kompanije") su vlasništvo Kompanije ili njenih licensora i slažete se da ne zahtevate ili tražite vlasništvo nad bilo kojim od tih prava intelektualne svojine Kompanije. Kompanija ovim garantuje, i vi time prihvatate, ličnu, ograničenu, neprenosivu, neekskluzivnu, opozivu i nedodeljivu licencu i dozvolu za preuzimanje i korišćenje Usluga na određenom kompatibilnom mobilnom uređaju isključivo za svoju ličnu, nekomercijalnu upotrebu. Možete dodatno. Dalje prihvatate i slažete se da nećete izmeniti, iznajmljivati, davati na lizing, pozajmljivati, davati u zakup, iznajmljivati, prodavati, distribuirati, kreirati ili stvarati Usluge i / ili prava intelektualne svojine Kompanije, osim u slučaju ako vam je Kompanija dala eksplicitnu pismenu dozvolu da to učinite. Slažete se da nikakvo pravo na intelektualnu svojinu Kompanije nije prebačeno na vas, i da ne ostvarujete nijedno drugo pravo, eksplicitno ili implicitno, za Usluge, osim prava izričito odobrenim ovim Uslovima. Prihvatate da svi znaci koji se pojavljuju kroz Usluge pripadaju Kompaniji, odnosno vlasnicima tih znakova, a zaštićeni su domaćim i međunarodnim zakonima o zaštitnim znakovima i autorskim pravima. Svako korišćenje bilo kojih znakova koji se pojavljuju kroz Usluge bez eksplicitne pismene saglasnosti vlasnika kompanije ili znaka, je strogo zabranjeno. ‘Playpoint’ je zaštitni znak Kompanije. Usluge se mogu preuzeti samo jednom i ne mogu se preneti, prodati, distribuirati, prikazivati izvoditi, kopirati, modifikovati ili koristiti na bilo koji način, u celini ili delimično, osim kako je određeno ovim uslovima. Garantujete da ćete koristiti samo interfejs koji obezbeđuje Kompanija da biste pristupili Uslugama. Slažete se da su nosioci prava, koji daju dozvolu Kompaniji da koristi za svoje Usluge njihove muzičke i druge sadržaje, obuhvaćeni u ovom smislu obimom zaštite ovog sporazuma, i da su sami ovlašćeni da sprovedu odredbe ovog sporazuma, koje se direktno odnose na njihov sadržaj. Vi znate da korišćenje muzičkih delova podleže uslovima korišćenja koji su navedeni u nastavku. Vi ne smete dozvoliti trećoj strani da kopira, menja, reprodukuje, prenosi, distribuira ili koristi na bilo koji drugi način muzičke delove, koje vi koristite ili primite, van granica dozvoljenih autorskim pravom. Vi se obavezujete da odmah obavestite Kompaniju o takvoj neovlašćenoj upotrebi. Sva prava koja vam nisu izričito dozvoljena ovim sporazumom, zadržava Kompanija i / ili njeni licencori.
	</p>

<h2>10. Sporazumi za usluge trećih strana / Transakcije sa oglašivačima i / ili Sponzorima
</h2>
	<p>Usluge mogu da uključuju i pristup Uslugama nezavisnih trećih strana, bilo direktno ili preko linkova na sajtove kojima upravljaju treće strane. Gde je razumno moguće, Kompanija treba da navede Usluge kao sadržaj treće strane. Iako mogu biti kobrendirane sa Kompanijom i zbog toga da uključuju zaštitne znakove Kompanije, sporazumi za usluge koje pružaju treće strane su direktno zaključeni između vas i trećih strana. Mi možemo takođe koristiti oglašivače i promotere da nam pomogne da pokrijemo troškove naših usluga. Kao uslov za korišćenje ovih usluga, slažete se da možemo da prikazujemo reklame i druge promocije na našem sajtu i isporučujemo reklame i promocije u vezi naših usluga. Takođe ste saglasni da neće pokušati da blokirate ili na drugi način ometate reklame ili promocije. Neke jurisdikcije nam ne dozvoljavaju da šaljemo reklame u vidu tekstualnih poruka bez vaše izričite saglasnosti, tako da se gore pomenuto možda ne može primeniti na vas. Mi nećemo deliti vaše lične podatke sa trećim stranama bez vašeg pristanka. Uključivanje bilo kakvih reklama ili promocija na našem sajtu ili u naše usluge ne predstavlja odobrenje takvog sadržaja, proizvoda, usluge ili kompanije od strane Kompanije. Mi nastojimo da osiguramo da sve reklame ili promocije budu prikladne za naše korisnike. Imate pravo da od nas tražite u bilo kom trenutku da vas ne kontaktiraju putem direktnog marketinga. Kompanija ne može učestvovati ili na bilo koji način biti odgovorna za bilo kakve transakcije u vezi sa uslugama koje nude treće strane, ili za bilo koji sadržaj ili informacije prezentovane u vezi bilo kojih usluga trećih strana.
	</p>

<h2>11. Privatnost i procesiranje podataka
</h2>
	<p>Slažete se da Kompanija prikuplja i obrađuje 'lične podatke' (npr. podaci koji bi se mogli koristiti da vas kontaktiraju, ili koje ste nam dali, kao što su ime i prezime, poštanska adresa, pol, starost, mišljenja, procene, znanja, broj telefona ili adresa e-pošte), "finansijski podaci" (odnosno brojevi kreditnih kartica, podaci o bankovnom računu ili lozinke) ili 'demografski i podaci o korišćenju' (npr. podaci koje pošaljete ili koje mi sakupimo, i koji nisu ni lični, niti finansijski podaci ali su neophodni za pravilno funkcionisanje i naplatu naših usluga, kao što su datum početka i kraja i količina vašeg korišćenja usluga), u skladu sa ostatkom ovog paragrafa kako bi ovaj veb sajt mogao funkcionisati (u daljem tekstu zajednički naziv "Lični podaci "). Kompanija pridaje veliku vrednost privatnosti svojih korisnika, međutim, možda ćemo preneti vaše lične podatke vašem operateru bežične telefonije ili gejtwej operateru da bi obezbedili naplatu. Dalje, možemo preneti vaše lične podatke vladinim agencijama, uključujući ali ne ograničavajući se na sudove i kancelarije javnih tužilaca za pravne postupke i sprečavanje zločina. Lični podaci prikupljeni od strane Kompanije mogu se čuvati i obrađivati u Holandiji ili bilo kojoj drugoj zemlji u kojoj kompanija ili njeni agenti imaju predstavništva. Korišćenjem Usluga, pristajete na svaki takav prenos ličnih podataka izvan vaše zemlje. Vaši lični podaci će biti izbrisani najkasnije u roku od šest meseci nakon prestanka vaše pretplate. Kompanija može sačuvati vaše lične podatke posle ovog datuma ako se to zahteva od strane zakona ili sporazuma. Kompanija će održavati procedure u skladu sa važećim zakonima za pojedince da dobiju pristup svojim ličnim podacima i ako je to moguće i na zahtev da ispravi ili izbriše lične podatke.
	</p>

<h2>12. Odricanje garancije i ograničenje odgovornosti
</h2>
	<p>Kompanija, njeni direktori, službenici, zaposleni, dobavljači i agenti (“Strane pribavljača”) odriču se bilo kakve odgovornosti za bilo kakvu štetu nastalu korišćenjem usluga. Vi izričito razumete i slažete se usluge pružaju na 'kao što jesu' i 'kao što je na raspolaganju " osnovi bez ikakvih garancija. Strane pribavljača se izričito odriču u najvećoj zakonom dozvoljenoj meri svih garancija, bilo izričitih, ili onih koje se podrazumevaju, određenih zakonom ili na drugi način, u vezi usluga, uključujući, bez ograničenja, implicitne uslove prodaje, vlasnistvo i prodajno stanje robe i imovine kao i namensku funkciju i krsenje autorskih prava. Strane pribavljača se odriču bilo kakve garancije u pogledu sigurnosti, pouzdanosti, pravovremenosti i izvođenja usluga. Strane pribavljača ne garantuju da će usluge zadovoljiti vaše zahteve ili će usluge funkcionisati neprekidno i bez grešaka. Nikakav savet ili podaci, bilo usmeni ili pismeni, koje ste dobili od nas ili putem naših usluga neće stvoriti nikakve garancije koje nisu izričito ovde pomenute. Vi se ne možete osloniti na takve podatke ili savet. Vi razumete i slažete se sa preuzimanjem i / ili korišćenjem Usluga, sadržaja, softvera i veb sajtova na sopstvenu odgovornost i rizik i da ćete biti isključivo vi biti odgovorni za bilo kakvu štetu na vašem računarskom sistemu, mobilnom telefonu ili za gubitak podataka koji je rezultat korišćenja usluga. Osim u jurisdikcijama gde su ove odredbe ograničene, slažete se da celokupna odgovornost Kompanije prema Vama ili bilo kojoj trećoj osobi, kao i za vaš ili ekskluzivni pravni lek bilo kojeg trećeg lica, u zakonu, u pravičnosti, ili drugačije u vezi usluga koje su pružene u skladu sa ovim sporazumom i/ili svako kršenje ovog sporazuma je isključivo ograničeno na iznos koji ste platili za takve Usluge za vreme trajanja ovog sporazuma. Osim u jurisdikcijama gde su takve odredbe ograničene, Strane pribavljača neće biti odgovorne za bilo kakve direktne, indirektne, slučajne, posebne, egzemplarne, kaznene, treće strane ili posledične štete (uključujući i štete za gubitak poslovnog profita, prekida poslovanja, gubitka poslovnih informacija i slično) koje proizilaze iz vašeg korišćenja, zloupotrebe ili nemogućnosti korišćenja usluga, sadržaja, softvera i veb sajta, čak i ako je Kompanija obaveštena o mogućnosti nastanka takvih šteta, do mere u kojoj država ne dozvoljava isključivanje ili ograničenja odgovornosti kako je izloženo u ovom tekstu, odgovornost Kompanije je ograničena na meru dozvoljenu zakonom u toj zemlji.
	</p>

<h2>13. Obeštećenje
</h2>
	<p>Slažete se da štitite Kompaniju i njene roditelje, članove, podružnice, filijale, pružaoce usluga, preduzetnike, agente, licensore, službenike, direktore, akcionare i zaposlene, od gubitka, odgovornosti, zahteva, tužbe ili potražnje, uključujući razumne advokatske nadoknade, načinjene od strane bilo koje treće strane nastale u vezi sa ili zbog (a) vašeg korišćenja Usluga, i (b) povreda s vaše strane ili vaših predstavnika i garancija postavljenih u ovim Uslovima. Vi ćete platiti i sve troškove, štete i troškove u vezi štete, uključujući bez ograničenja, razumne advokatske naknade i troškove koji su dodeljeni da se plate ili kojima je Kompanija izvrgnuta u vezi sa ili proizlazeći iz bilo koje takve tužbe, parnice, akcije, zahteva ili drugog postupka.
	</p>

<h2>14. Prekid i otkazivanje usluga, pravo opozivanja
</h2>
	<p>Da otkažete pretplatu na Usluge putem tekstualne poruke, pošaljite STOP na top ili pošaljite e-poštu na c U prvoj situaciji prekid će stupiti na snagu odmah po primanju zahteva za prekid. U drugim slučajevima, otkazivanje će jedino stupiti na snagu u roku od 48 sati po primanju zahteva za prekid. Troškovi se mogu i dalje pojaviti na računu od vašeg pružaoca bežičnih usluga sledećeg meseca, ako fakturiše retroaktivno.
	</p>
<p>Slažete se da Kompanija, po svom nahođenju, može da u bilo kom trenutku ukine Vaše korišćenje Usluga i da ukloni ili odbaci bilo koji sadržaj u okviru tih usluga, ukoliko Kompanija smatra da ste prekršili ili se niste ponašali u skladu sa ovim Uslovima. Ukoliko Vi otkažete svoj nalog ili pretplatu iz bilo kojeg razloga, Kompanija vam neće refundirati plaćene iznose do tog dana, osim ako to nije izričito navedeno u bilo kojoj stavki ovih Uslova.
</p>
<p>Klijenti u Evropskoj Uniji takođe imaju zakonsko pravo da se povuku iz ovog sporazuma u roku od minimalnog perioda od 14 radnih dana nakon datuma stupanja na snagu ovog sporazuma (Period opozivanja). Kompanija je za vas odredila 14 radnih dana kao Period opozivanja, pod uslovom da se vaše pravo opozivanja odmah prekida ukoliko vam je pružen pristup Uslugama pre kraja Perioda opozivanja. Kako bi se povukli iz Sporazuma u toku Perioda opozivanja, pošaljite obaveštenje o prekidu putem e-pošte na support.sr@mypacks.com ili poštom na Root Technologies B.V, 4001 KZ Tiel, Nederland, pri čemu pri komunikaciji treba da jasno naznačite svoje ime, adresu i broj telefona, i sa poštanskim žigom u toku Perioda opozivanja.
</p>
<h2>15. Različite odredbe
</h2>
	<p>Obaveštenja i najave. Izuzev ako nije izričito drugačije ovde navedeno, sva obaveštenja moraju Kompaniji biti dostavljena u pisanom obliku na sledeću adresu: Root Technologies B.V, Damstraat 2, 4001 KZ Tiel, Nederland, Nederland
	</p><p>Kada pristupite ili koristite Usluge ili šaljete SMS, e-poštu ili druge vrste komunikacije Kompaniji, komunicirate s nama putem elektronske komunikacije, znači slažete se da primate elektronsku poštu od strane Kompanije. Slažete se da sporazumi, obaveštenja, otkrivanja i druga komunikacija koju vam Kompanija pruža elektronskim putem zadovoljava sve pravne uslove i da takva komunikacija bude u pisanoj formi. Izuzev kao što je predviđeno u “Prekid i otkazivanje usluga, pravo opozivanja” Delu , obaveštenja poslata poštom smatraće se primljenim u roku od sedam dana nakon što su poslati a obaveštenja postavljena na veb sajtu Kompanije ili poslata e-poštom ili putem tekstualne poruke smatraće se primljenim na radni dan, jedan dan nakon što je objavljeno ili poslato.
</p>
<p>
Prenošenje: Ne možete dodeliti ili preneti ni na koji način ovaj sporazum niti bilo koja vaša prava. Kompanija će imati pravo da dodeli svoja prava i obaveže pod ovim sporazumom i sve primljeno zasnovano na ovom sporazumu trećoj strani nakon što vam je poslala obaveštenje u pisanoj formi, pod uslovom da je takvo dodeljivanje načinjeno pod uslovima koji nisu lošiji po vas nego oni u Uslovima.
</p>
<p>
Promena uslova. Priznajete i slažete se da ovi uslovi podležu promenama Kompanije u svako vreme, čije će promene stupati na snagu nakon uvođenja takvih promena na veb sajtu. Bilo koja upotreba usluga nakon takvih promena znači prihvatanje takvih promena s vaše strane.
</p>
<p>
Drugi uslovi, celokupni sporazum. Ovi Uslovi su dodatak bilo kojim uslovima korišćenja Kompanije ili treće strane primenljivim na Usluge, koji mogu biti objavljeni u vezi takvih Usluga (“Posebni Uslovi”).U slučaju bilo kakvog neslaganja između uslova i Posebnih uslova, ovi drugi će prevladati. Ovi uslovi i bilo koji drugi uslovi ili dokumenti koji se odnose na ovo predstavljaju vaš potpuni sporazum sa Kompanijom u odnosu na vaše korišćenje Usluga. Razumete i slažete se osim ako nije izričito drugačije navedeno da ovaj sporazum nije namenjen za savetodavanje i ne daje vam nikakva prava niti pravni lek u vezi bilo koje osobe drugačije od strana ovog sporazuma.
</p>
<p>
Odvojivost. Ako se bilo koji deo ovog sporazuma smatra nevažećim ili neprimenljivim, taj deo će se tumačiti na način u skladu sa važećim zakonom, da prikaže, što tačnije moguće, originalne namere strana, a preostali delovi će ostati punosnažni i punovažeći .
</p>
<p>
Odustajanje. Neuspeh Kompanije da podnese tužbu ili se odbrani u skladu sa ovim sporazumom ili u suprotnom neće odustati od te tužbe ili odbrane. Naslovi koji se koriste u ovim Uslovima su tu samo iz praktičnih razloga, i neće imati nikakvog uticaja na tumačenje pravne primenljivosti termina.

Opstanak. U slučaju da ovaj ugovor prestaje da važi kako je predviđeno ovde, Delovi ovih uslova koji su zbog svoje prirode tako napravljeni da opstanu, opstaće uprkos isticanju roka ili prestanku.
</p>
<p>
Upravna prava i nadležnosti. Ovaj sporazum i vaše korišćenje veb sajta i usluga regulisaće se i tumačiće se u skladu sa zakonima Holandije. Vi se i dalje slažete da za bilo koje pitanje koje proizilazi iz ili se odnosi na ovaj sporazum da će podlegati sudovima i pravnim tribunalima koji se nalaze u Tiel, Holandiji.
</p>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
    </div>
</main>
<!-- End Main -->
@include('footer.'.App::getLocale())
@endsection

@section('scripts')
@endsection
